---
- hosts: Server1
  tasks:
    - name: print os family
      shell: echo "the family is {{ansible_os_family}}" > /home/{{ansible_user_id}}/family.txt
    - name: Print Default machine nic name
      debug: msg="{{ansible_default_ipv4.interface}}"
    - name: Register ls results variable
      command: ls
      register: dirs
    - name: Print dirs variable from console
      debug:
       msg: "{{dirs}}" 


