---
- name: Demo Loops
  hosts: Server1
  become: yes
  tasks:
  - name: Create a file
    shell: echo'Begin file' > /home/prateek/loops.txt
  - name:install packages
    shell: echo "{{item}}"  >> /home/prateek/loops.txt
    with_items:
      - vim
      - nano
      - python

